server:
  port: 8083
spring:
  application:
    name: server-category
swagger:
  enabled: true
  groupName: server-user
  basePackage: com.xwh.controller
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数